name: Ubuntu_Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Install dependencies
      run: |
        apt install patchelf
        python -m pip install --upgrade pip
        python -m pip install -e .
        python -m pip install pytest
    - name: Run Tests
      run: |
        pytest tests
